# Generated by Django 6.0.2 on 2026-02-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiceMacro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=100)),
                ('num_dice', models.IntegerField()),
                ('sides', models.IntegerField()),
                ('modifier', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('user_id', 'name')},
            },
        ),
    ]
